name: CI
on: pull_request

jobs:
  ci:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2
      - name: Setup NodeJs
        uses: actions/setup-node@v2
        with:
          node-version: "16.13"
      - name: Install Dependencies
        run: npm install
      - name: Run test
        run: npm test
